#!/bin/sh

while true; do
  echo "$(date): Starting ausnimbus idler"
  echo
  oc get ns -o name -l idle=true | cut -c 11- | while read ns;
    do echo "$(date): Idling resources in $ns";
      oc idle -n $ns --all;
      echo;
    done
  echo

  # Sleep for 12 hours
  sleep 43200
done
