#!/bin/sh

# create a .kubeconfig
oc project openshift

while true; do
  echo "$(date): Starting ausnimbus idler"
  oc get ns -o name -l idle=true | cut -c 11- | while read ns;
    do echo "$(date): Idling resources in $ns";
      oc idle -n $ns --all;
      echo;
    done
  echo

  sleep $DELAY
done
